services:
  backend:
    build: ./
    volumes:
      - ./data/primary:/data
    environment:
      - SPRING_PROFILES_ACTIVE=primary
      - BACKUP_URL=http://backend-backup:8080
      - REPLICATION_SECRET=ZbqRNYRzXbfr6bdbrzmwMinqOhYWwiA9vvXNxPRnhY6
      - DATA_DIR=/data
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health
      - JWT_SECRET=ZbqRNYRzXbfr6bdbrzmwMinqOhYWwiA9vvXNxPRnhY6
    container_name: backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 2s
      retries: 3
    expose:
      - "8080"
    restart: unless-stopped

  backend-backup:
    build: ./
    volumes:
      - ./data/secondary:/data
    environment:
      - SERVER_ROLE=secondary
      - SPRING_PROFILES_ACTIVE=secondary
      - REPLICATION_SECRET=ZbqRNYRzXbfr6bdbrzmwMinqOhYWwiA9vvXNxPRnhY6
      - DATA_DIR=/data
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health
      - JWT_SECRET=ZbqRNYRzXbfr6bdbrzmwMinqOhYWwiA9vvXNxPRnhY6
    container_name: backend-backup
    expose:
      - "8080"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - backend-backup
    restart: unless-stopped
